### PR TITLE
race fix

### PR DESCRIPTION
**Pull request by daveads**
https://github.com/terrastruct/d2/pull/2130#pullrequestreview-2338424150

### CODE REVIEW

**Comment by daveads** [comment]
@alixander can you attend to this... then i will do a test on the test-branch to be sure.

**Review by alixander — COMMENTED** [review]
can you sign your commit please? It's an org-wide setting we have for contributions.

**Comment by daveads** [comment]
> can you sign your commit please? It's an org-wide setting we have for contributions.

am not familiar with this.. how do i do this ?

**Comment by daveads** [comment]
@alixander  done.

**Comment by daveads** [comment]
@alixander  it's ready now... merge so i can.. run a test

**Comment by daveads** [comment]
> Can you explain what was happening that caused the race in those tests and how this fixes it?

The race condition occurs because s.Serve(l) and s.Shutdown(ctx) which were accessing the server's internal state concurrently, the Serve method doesn't know about the Shutdown call, and vice versa, leading to potential data races and undefined behavior.

**Comment by daveads** [comment]
and the implementation attempts to addressed this issues by

* using a Coordinated Shutdown and
* Channel for Server Closure

**Review by alixander — APPROVED** [review]
merging tentatively to see if it fixes

**Comment by alixander** [comment]
looks like one of the commits is not signed. can you either sign it or squash your commits

**Comment by daveads** [comment]
> looks like one of the commits is not signed. can you either sign it or squash your commits

@alixander

**Pull request merged**
